import type { AnalysisResult } from "../../types";
import { generateTextContent } from "./txtUtil";
import { downloadFile } from "../helpers/downloadFile";
import { generateMarkdownContent } from "./mdUtil";
import { PdfExporter } from "../helpers/pdfFunctions";
import { generatePdfContents } from "./pdfUtil";

// Generate TXT export
export function exportToTxt(analysisResult: AnalysisResult): void {
  const content = generateTextContent(analysisResult);
  const blob = new Blob([content], { type: "text/plain" });
  downloadFile(blob, `${analysisResult.company_name}_analysis.txt`);
}

// Generate Markdown export
export function exportToMarkdown(analysisResult: AnalysisResult): void {
  const content = generateMarkdownContent(analysisResult);
  const blob = new Blob([content], { type: "text/markdown" });
  downloadFile(blob, `${analysisResult.company_name}_analysis.md`);
}

// Generate PDF export
export async function exportToPdf(analysisResult: AnalysisResult) {
  const pdf = new PdfExporter();

  try {
    // Title Page
    pdf.addText("Business Analysis Report", 20, "bold");
    pdf.addText(analysisResult.company_name, 16);
    pdf.addText(`Generated on: ${new Date().toLocaleDateString()}`, 10);

    // Generate all PDF contents
    await generatePdfContents(pdf, analysisResult);

    // Footer
    pdf.checkPageBreak(30);
    pdf.addText(
      "Generated by InsightFlow - AI-Powered Competitive Intelligence",
      8
    );

    // Save PDF
    pdf.save(`${analysisResult.company_name}_analysis.pdf`);
  } catch (err) {
    console.error("Failed to generate PDF:", err);
    exportToTxt(analysisResult); // fallback
  }
}